FROM arm32v7/debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libsdl2-dev \
	ca-certificates \
        cmake \
        cargo \
        wget \
        squashfs-tools \
        zip \
	libfltk1.3-dev \ 
	libfltk-images1.3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

CMD ["/bin/bash"]
